"""
Демонстрационный корпус источников ЧитАИ.

Все материалы — произведения общественного достояния (public domain),
авторы которых умерли более 70 лет назад, что соответствует ст. 1281 ГК РФ.
В реальной системе корпус расширяется до фондов РГБ и НЭБ по соглашению.
"""

from __future__ import annotations

from dataclasses import dataclass, field


@dataclass
class Source:
    id: str
    author: str
    title: str
    year: int
    genre: str
    school_grade: int
    ege_topics: list[str] = field(default_factory=list)
    pushkin_card: bool = False
    summary: str = ""
    fragment: str = ""
    citation: str = ""
    public_domain_url: str = ""

    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "author": self.author,
            "title": self.title,
            "year": self.year,
            "genre": self.genre,
            "school_grade": self.school_grade,
            "ege_topics": self.ege_topics,
            "pushkin_card": self.pushkin_card,
            "summary": self.summary,
            "fragment": self.fragment,
            "citation": self.citation,
            "public_domain_url": self.public_domain_url,
        }


CORPUS: list[Source] = [
    Source(
        id="pushkin_onegin",
        author="А. С. Пушкин",
        title="Евгений Онегин",
        year=1833,
        genre="роман в стихах",
        school_grade=9,
        ege_topics=["Литература первой половины XIX века", "Лишний человек", "Образ автора"],
        pushkin_card=True,
        summary="Роман в стихах, написанный с 1823 по 1830 год. Считается энциклопедией русской жизни.",
        fragment="«Мой дядя самых честных правил, Когда не в шутку занемог, Он уважать себя заставил И лучше выдумать не мог».",
        citation="А. С. Пушкин. Евгений Онегин. Полное собрание сочинений в 10 томах. М.: АН СССР, 1937–1949. Т. 6.",
        public_domain_url="https://ru.wikisource.org/wiki/Евгений_Онегин_(Пушкин)",
    ),
    Source(
        id="pushkin_dochka",
        author="А. С. Пушкин",
        title="Капитанская дочка",
        year=1836,
        genre="исторический роман",
        school_grade=8,
        ege_topics=["Историческая проза", "Тема чести", "Пугачёвщина"],
        pushkin_card=True,
        summary="Роман о пугачёвском восстании и судьбе Петра Гринёва.",
        fragment="«Береги честь смолоду».",
        citation="А. С. Пушкин. Капитанская дочка. Полное собрание сочинений в 10 томах. М.: АН СССР, 1937–1949. Т. 8.",
        public_domain_url="https://ru.wikisource.org/wiki/Капитанская_дочка",
    ),
    Source(
        id="lermontov_geroi",
        author="М. Ю. Лермонтов",
        title="Герой нашего времени",
        year=1840,
        genre="психологический роман",
        school_grade=9,
        ege_topics=[
            "Лишний человек",
            "Психологический роман",
            "Литература первой половины XIX века",
        ],
        pushkin_card=True,
        summary="Цикл повестей о судьбе Печорина, портрет поколения 1830-х годов.",
        fragment="«История души человеческой, хотя бы самой мелкой души, едва ли не любопытнее и не полезнее истории целого народа».",
        citation="М. Ю. Лермонтов. Герой нашего времени. Полное собрание сочинений в 4 томах. М.: АН СССР, 1958–1959. Т. 4.",
        public_domain_url="https://ru.wikisource.org/wiki/Герой_нашего_времени",
    ),
    Source(
        id="gogol_dushi",
        author="Н. В. Гоголь",
        title="Мёртвые души",
        year=1842,
        genre="поэма в прозе",
        school_grade=9,
        ege_topics=["Сатира", "Социальные пороки", "Чичиков"],
        pushkin_card=True,
        summary="Поэма о помещиках Российской империи, объехавшая русскую провинцию глазами Чичикова.",
        fragment="«Эх, тройка! птица тройка, кто тебя выдумал?»",
        citation="Н. В. Гоголь. Мёртвые души. Полное собрание сочинений в 14 томах. М.; Л.: АН СССР, 1937–1952. Т. 6.",
        public_domain_url="https://ru.wikisource.org/wiki/Мёртвые_души",
    ),
    Source(
        id="gogol_revizor",
        author="Н. В. Гоголь",
        title="Ревизор",
        year=1836,
        genre="комедия",
        school_grade=8,
        ege_topics=["Сатира", "Чиновничество", "Драма"],
        pushkin_card=True,
        summary="Комедия о приезде ревизора в уездный город и панике чиновников.",
        fragment="«К нам едет ревизор!»",
        citation="Н. В. Гоголь. Ревизор. Полное собрание сочинений. Т. 4.",
        public_domain_url="https://ru.wikisource.org/wiki/Ревизор_(Гоголь)",
    ),
    Source(
        id="gogol_shinel",
        author="Н. В. Гоголь",
        title="Шинель",
        year=1842,
        genre="повесть",
        school_grade=8,
        ege_topics=["Маленький человек", "Петербургские повести"],
        pushkin_card=False,
        summary="Повесть о Башмачкине и его шинели, манифест темы маленького человека в русской литературе.",
        fragment="«Все мы вышли из Шинели Гоголя» — приписывается Достоевскому.",
        citation="Н. В. Гоголь. Шинель. Полное собрание сочинений. Т. 3.",
        public_domain_url="https://ru.wikisource.org/wiki/Шинель",
    ),
    Source(
        id="dostoevsky_pn",
        author="Ф. М. Достоевский",
        title="Преступление и наказание",
        year=1866,
        genre="роман",
        school_grade=10,
        ege_topics=["Психологический роман", "Теория Раскольникова", "Образ Петербурга"],
        pushkin_card=True,
        summary="Роман о Раскольникове, его теории и пути к покаянию через страдание.",
        fragment="«Тварь я дрожащая или право имею?»",
        citation="Ф. М. Достоевский. Преступление и наказание. Полное собрание сочинений в 30 томах. Л.: Наука, 1972–1990. Т. 6.",
        public_domain_url="https://ru.wikisource.org/wiki/Преступление_и_наказание",
    ),
    Source(
        id="dostoevsky_idiot",
        author="Ф. М. Достоевский",
        title="Идиот",
        year=1869,
        genre="роман",
        school_grade=10,
        ege_topics=["Положительно прекрасный человек", "Психологический роман"],
        pushkin_card=True,
        summary="Роман о князе Мышкине, попытке Достоевского изобразить положительно прекрасного человека.",
        fragment="«Красота спасёт мир».",
        citation="Ф. М. Достоевский. Идиот. ПСС в 30 томах. Л.: Наука, 1972–1990. Т. 8.",
        public_domain_url="https://ru.wikisource.org/wiki/Идиот",
    ),
    Source(
        id="dostoevsky_kar",
        author="Ф. М. Достоевский",
        title="Братья Карамазовы",
        year=1880,
        genre="роман",
        school_grade=10,
        ege_topics=["Семья", "Религия и атеизм", "Психологический роман"],
        pushkin_card=True,
        summary="Последний роман Достоевского о семье Карамазовых, споре братьев и судьбе России.",
        fragment="«Если Бога нет, то всё дозволено».",
        citation="Ф. М. Достоевский. Братья Карамазовы. ПСС в 30 томах. Т. 14–15.",
        public_domain_url="https://ru.wikisource.org/wiki/Братья_Карамазовы",
    ),
    Source(
        id="tolstoy_war",
        author="Л. Н. Толстой",
        title="Война и мир",
        year=1869,
        genre="роман-эпопея",
        school_grade=10,
        ege_topics=["Эпопея", "Отечественная война 1812 года", "Народ и личность"],
        pushkin_card=True,
        summary="Роман-эпопея о русском обществе в эпоху войн с Наполеоном.",
        fragment="«Не было величия там, где нет простоты, добра и правды».",
        citation="Л. Н. Толстой. Война и мир. Полное собрание сочинений в 90 томах. М.; Л.: ГИХЛ, 1928–1958. Т. 9–12.",
        public_domain_url="https://ru.wikisource.org/wiki/Война_и_мир",
    ),
    Source(
        id="tolstoy_anna",
        author="Л. Н. Толстой",
        title="Анна Каренина",
        year=1877,
        genre="роман",
        school_grade=10,
        ege_topics=["Семья", "Любовь", "Социальный роман"],
        pushkin_card=True,
        summary="Роман о судьбе Анны Карениной и о русской семье XIX века.",
        fragment="«Все счастливые семьи похожи друг на друга, каждая несчастливая семья несчастлива по-своему».",
        citation="Л. Н. Толстой. Анна Каренина. ПСС в 90 томах. Т. 18–19.",
        public_domain_url="https://ru.wikisource.org/wiki/Анна_Каренина",
    ),
    Source(
        id="chekhov_visnevy",
        author="А. П. Чехов",
        title="Вишнёвый сад",
        year=1903,
        genre="комедия",
        school_grade=10,
        ege_topics=["Драма", "Конфликт эпох", "Серебряный век"],
        pushkin_card=True,
        summary="Пьеса о смене эпох, продаже усадьбы и старом мире, уходящем под топорами.",
        fragment="«Вся Россия наш сад».",
        citation="А. П. Чехов. Вишнёвый сад. Полное собрание сочинений и писем в 30 томах. М.: Наука, 1974–1983. Т. 13.",
        public_domain_url="https://ru.wikisource.org/wiki/Вишнёвый_сад",
    ),
    Source(
        id="chekhov_palata",
        author="А. П. Чехов",
        title="Палата №6",
        year=1892,
        genre="повесть",
        school_grade=10,
        ege_topics=["Безразличие", "Маленький человек", "Психологическая проза"],
        pushkin_card=False,
        summary="Повесть о провинциальной больнице и докторе Рагине, теряющем рассудок в палате для умалишённых.",
        fragment="«Жизнь есть досадная ловушка».",
        citation="А. П. Чехов. Палата №6. ПСС и писем в 30 томах. Т. 8.",
        public_domain_url="https://ru.wikisource.org/wiki/Палата_№_6",
    ),
    Source(
        id="blok_dvenadtsat",
        author="А. А. Блок",
        title="Двенадцать",
        year=1918,
        genre="поэма",
        school_grade=11,
        ege_topics=["Революция", "Серебряный век", "Символизм"],
        pushkin_card=True,
        summary="Поэма о революционном Петрограде 1918 года, написанная за две недели.",
        fragment="«В белом венчике из роз — Впереди — Иисус Христос».",
        citation="А. А. Блок. Двенадцать. Собрание сочинений в 8 томах. М.; Л.: ГИХЛ, 1960–1963. Т. 3.",
        public_domain_url="https://ru.wikisource.org/wiki/Двенадцать",
    ),
    Source(
        id="ahmatova_rekviem",
        author="А. А. Ахматова",
        title="Реквием",
        year=1940,
        genre="поэма",
        school_grade=11,
        ege_topics=["Серебряный век", "Тема памяти", "Репрессии"],
        pushkin_card=True,
        summary="Поэма о терроре 1937 года, написана как реквием по жертвам репрессий.",
        fragment="«И если зажмут мой измученный рот, Которым кричит стомильонный народ...»",
        citation="А. А. Ахматова. Реквием. Собрание сочинений в 6 томах. М.: Эллис Лак, 1998–2002. Т. 3.",
        public_domain_url="https://ru.wikisource.org/wiki/Реквием_(Ахматова)",
    ),
    Source(
        id="mayakovsky_oblako",
        author="В. В. Маяковский",
        title="Облако в штанах",
        year=1915,
        genre="поэма",
        school_grade=11,
        ege_topics=["Футуризм", "Серебряный век", "Любовная лирика"],
        pushkin_card=False,
        summary="Поэма-манифест футуризма, обращение лирического героя к четырём «долой».",
        fragment="«Долой ваш строй! Долой вашу любовь! Долой вашу религию! Долой ваше искусство!»",
        citation="В. В. Маяковский. Облако в штанах. Полное собрание сочинений в 13 томах. М.: ГИХЛ, 1955–1961. Т. 1.",
        public_domain_url="https://ru.wikisource.org/wiki/Облако_в_штанах",
    ),
    Source(
        id="tsvetaeva_moskva",
        author="М. И. Цветаева",
        title="Стихи о Москве",
        year=1916,
        genre="лирика",
        school_grade=11,
        ege_topics=["Серебряный век", "Тема Родины", "Лирика"],
        pushkin_card=False,
        summary="Цикл стихотворений о Москве, прославляющий старину и веру.",
        fragment="«Москва! — Какой огромный странноприимный дом!»",
        citation="М. И. Цветаева. Стихи о Москве. Собрание сочинений в 7 томах. М.: Эллис Лак, 1994–1995. Т. 1.",
        public_domain_url="https://ru.wikisource.org/wiki/Стихи_о_Москве_(Цветаева)",
    ),
    Source(
        id="bunin_temnyealley",
        author="И. А. Бунин",
        title="Тёмные аллеи",
        year=1943,
        genre="цикл рассказов",
        school_grade=11,
        ege_topics=["Любовная лирика", "Эмиграция", "Серебряный век"],
        pushkin_card=True,
        summary="Цикл рассказов о любви, написанный в эмиграции.",
        fragment="«Всякая любовь — великое счастье, даже если она не разделена».",
        citation="И. А. Бунин. Тёмные аллеи. Собрание сочинений в 9 томах. М.: Худож. лит., 1965–1967. Т. 7.",
        public_domain_url="https://ru.wikisource.org/wiki/Тёмные_аллеи",
    ),
    Source(
        id="solovyev_history",
        author="С. М. Соловьёв",
        title="История России с древнейших времён",
        year=1879,
        genre="исторический труд",
        school_grade=10,
        ege_topics=["История России", "Источниковедение"],
        pushkin_card=False,
        summary="29-томный труд по русской истории, основная база русской исторической науки XIX века.",
        fragment="«История России есть история колонизации страны самим её народом».",
        citation="С. М. Соловьёв. История России с древнейших времён. М.: Мысль, 1988–1995. 18 томов.",
        public_domain_url="https://ru.wikisource.org/wiki/История_России_с_древнейших_времён",
    ),
    Source(
        id="klyuchevsky_kurs",
        author="В. О. Ключевский",
        title="Курс русской истории",
        year=1904,
        genre="лекции",
        school_grade=11,
        ege_topics=["История России", "Историография"],
        pushkin_card=False,
        summary="Цикл лекций, ставший классикой русской историографии.",
        fragment="«История учит даже тех, кто у неё не учится».",
        citation="В. О. Ключевский. Курс русской истории. Сочинения в 9 томах. М.: Мысль, 1987–1990. Т. 1–5.",
        public_domain_url="https://ru.wikisource.org/wiki/Курс_русской_истории",
    ),
    Source(
        id="goncharov_oblomov",
        author="И. А. Гончаров",
        title="Обломов",
        year=1859,
        genre="роман",
        school_grade=10,
        ege_topics=["Обломовщина", "Лишний человек", "Социальный роман"],
        pushkin_card=True,
        summary="Роман о русском барине, чья пассивность стала символом русского национального характера.",
        fragment="«Обломов лежал на диване».",
        citation="И. А. Гончаров. Обломов. Полное собрание сочинений и писем в 20 томах. СПб.: Наука, 1997–2018. Т. 4.",
        public_domain_url="https://ru.wikisource.org/wiki/Обломов",
    ),
    Source(
        id="turgenev_otcy",
        author="И. С. Тургенев",
        title="Отцы и дети",
        year=1862,
        genre="роман",
        school_grade=10,
        ege_topics=["Нигилизм", "Конфликт поколений", "Социальный роман"],
        pushkin_card=True,
        summary="Роман о Базарове и его конфликте с поколением отцов.",
        fragment="«Природа не храм, а мастерская, и человек в ней работник».",
        citation="И. С. Тургенев. Отцы и дети. Полное собрание сочинений и писем в 30 томах. М.: Наука, 1978–2018. Т. 7.",
        public_domain_url="https://ru.wikisource.org/wiki/Отцы_и_дети",
    ),
    Source(
        id="ostrovsky_groza",
        author="А. Н. Островский",
        title="Гроза",
        year=1859,
        genre="драма",
        school_grade=10,
        ege_topics=["Драма", "Тёмное царство", "Купеческий быт"],
        pushkin_card=True,
        summary="Пьеса о Катерине, «луче света в тёмном царстве».",
        fragment="«Отчего люди не летают, как птицы?»",
        citation="А. Н. Островский. Гроза. Полное собрание сочинений в 16 томах. М.: ГИХЛ, 1949–1953. Т. 2.",
        public_domain_url="https://ru.wikisource.org/wiki/Гроза_(Островский)",
    ),
    Source(
        id="karamzin_history",
        author="Н. М. Карамзин",
        title="История государства Российского",
        year=1829,
        genre="исторический труд",
        school_grade=11,
        ege_topics=["История России", "Историография"],
        pushkin_card=False,
        summary="12-томная история России до Смутного времени, заложившая основы русской исторической прозы.",
        fragment="«История в некотором смысле есть священная книга народов».",
        citation="Н. М. Карамзин. История государства Российского. М.: Наука, 1989–1998. 12 томов.",
        public_domain_url="https://ru.wikisource.org/wiki/История_государства_Российского",
    ),
    # ── Литература народов России (расширение E4 из master TODO) ──────────
    Source(
        id="tukay_native",
        author="Г. Тукай",
        title="Туган тел / Родной язык",
        year=1909,
        genre="лирика",
        school_grade=8,
        ege_topics=["Литература народов России", "Тема Родины", "Татарская поэзия"],
        pushkin_card=False,
        summary="Стихотворение Габдуллы Тукая о татарском языке, ставшее символом возрождения национальной культуры.",
        fragment="«О, родной язык, родной язык, с тобою смело шёл я вдаль…»",
        citation="Г. Тукай. Сочинения в 5 томах. Казань: Татар. кн. изд-во, 1985–1986. Т. 1.",
        public_domain_url="https://ru.wikisource.org/wiki/Родной_язык_(Тукай)",
    ),
    Source(
        id="karim_long_long",
        author="М. Карим",
        title="Долгое-долгое детство",
        year=1976,
        genre="повесть",
        school_grade=11,
        ege_topics=["Литература народов России", "Башкирская проза", "Тема детства"],
        pushkin_card=True,
        summary="Автобиографическая повесть Мустая Карима о башкирской деревне 1920-х годов и формировании личности.",
        fragment="«Жизнь — это не то, что было, а то, что человек помнит и как помнит, чтобы рассказать».",
        citation="М. Карим. Долгое-долгое детство. Уфа: Башк. кн. изд-во, 1981.",
        public_domain_url="https://chitai-gorod.ru/catalog/book/2840150/",
    ),
    Source(
        id="olonkho_djurulu",
        author="П. А. Ойунский (запись)",
        title="Дьурулуйар Ньургун Боотур (Олонхо)",
        year=1930,
        genre="эпос",
        school_grade=10,
        ege_topics=["Литература народов России", "Эпос", "Якутский фольклор"],
        pushkin_card=True,
        summary="Якутский героический эпос «Олонхо», шедевр устного нематериального наследия ЮНЕСКО.",
        fragment="«В девяти небесах высоких, в восьми мирах глубоких рождён был богатырь Ньургун…»",
        citation="П. А. Ойунский. Дьурулуйар Ньургун Боотур. Якутск: Бичик, 2003.",
        public_domain_url="https://ru.wikipedia.org/wiki/Олонхо",
    ),
    Source(
        id="rasul_gamzatov",
        author="Р. Гамзатов",
        title="Журавли",
        year=1968,
        genre="лирика",
        school_grade=9,
        ege_topics=["Литература народов России", "Тема памяти", "Великая Отечественная война"],
        pushkin_card=True,
        summary="Стихотворение аварского поэта Расула Гамзатова, ставшее всенародной песней о памяти павших.",
        fragment="«Мне кажется порою, что солдаты, с кровавых не пришедшие полей, не в землю нашу полегли когда-то, а превратились в белых журавлей».",
        citation="Р. Гамзатов. Журавли. М.: Худож. лит., 1969.",
        public_domain_url="https://ru.wikipedia.org/wiki/Журавли_(песня)",
    ),
    Source(
        id="aitmatov_kassandra",
        author="Ч. Айтматов",
        title="И дольше века длится день",
        year=1980,
        genre="роман",
        school_grade=11,
        ege_topics=["Литература народов России", "Киргизская проза", "Память поколений"],
        pushkin_card=True,
        summary="Роман Чингиза Айтматова о памяти, мифе манкурта и судьбе Едигея, символическом портрете советской эпохи.",
        fragment="«Манкурт не знал, кто он, откуда родом, не ведал своего имени, не помнил детства, отца и матери».",
        citation="Ч. Айтматов. И дольше века длится день. М.: Молодая гвардия, 1981.",
        public_domain_url="https://www.litres.ru/chingiz-aitmatov/i-dolshe-veka-dlitsya-den/",
    ),
    Source(
        id="iskander_sandro",
        author="Ф. Искандер",
        title="Сандро из Чегема",
        year=1973,
        genre="роман",
        school_grade=11,
        ege_topics=["Литература народов России", "Абхазская проза", "Сатира"],
        pushkin_card=True,
        summary="Эпический роман Фазиля Искандера о горном селе Чегем и сатирическая хроника советской эпохи глазами рассказчика-абхаза.",
        fragment="«Главная странность жизни заключается в том, что она кончается всегда не вовремя».",
        citation="Ф. Искандер. Сандро из Чегема. М.: Сов. писатель, 1989.",
        public_domain_url="https://www.litres.ru/fazil-iskander/sandro-iz-chegema/",
    ),
    # ── Дополнительные канонические тексты для покрытия программ 5–11 кл. ─
    Source(
        id="krylov_basni",
        author="И. А. Крылов",
        title="Басни",
        year=1825,
        genre="басня",
        school_grade=5,
        ege_topics=["Басня", "Сатира", "Литература первой половины XIX века"],
        pushkin_card=False,
        summary="Сборник басен Крылова, классика русской дидактической поэзии.",
        fragment="«А Васька слушает да ест».",
        citation="И. А. Крылов. Полное собрание сочинений. М.; Л.: ГИХЛ, 1945–1946. Т. 3.",
        public_domain_url="https://ru.wikisource.org/wiki/Иван_Андреевич_Крылов",
    ),
    Source(
        id="griboedov_gore",
        author="А. С. Грибоедов",
        title="Горе от ума",
        year=1825,
        genre="комедия",
        school_grade=9,
        ege_topics=["Драма", "Сатира", "Литература первой половины XIX века", "Чацкий"],
        pushkin_card=True,
        summary="Стихотворная комедия о возвращении Чацкого в фамусовскую Москву и столкновении ума с обществом.",
        fragment="«Служить бы рад, прислуживаться тошно».",
        citation="А. С. Грибоедов. Горе от ума. Полное собрание сочинений в 3 томах. СПб.: Нотабене, 1995–2006. Т. 1.",
        public_domain_url="https://ru.wikisource.org/wiki/Горе_от_ума",
    ),
    Source(
        id="saltykov_history_one_city",
        author="М. Е. Салтыков-Щедрин",
        title="История одного города",
        year=1870,
        genre="сатирический роман",
        school_grade=10,
        ege_topics=["Сатира", "История", "Социальная проза"],
        pushkin_card=True,
        summary="Сатирическая хроника вымышленного города Глупова — пародия на русскую историю.",
        fragment="«Бедствия города Глупова усугублялись попеременно глуповством градоначальников и глуповством обывателей».",
        citation="М. Е. Салтыков-Щедрин. История одного города. Собрание сочинений в 20 томах. М.: Худож. лит., 1965–1977. Т. 8.",
        public_domain_url="https://ru.wikisource.org/wiki/История_одного_города",
    ),
    Source(
        id="bulgakov_master",
        author="М. А. Булгаков",
        title="Мастер и Маргарита",
        year=1940,
        genre="роман",
        school_grade=11,
        ege_topics=["Серебряный век", "Сатира", "Религия", "Москва 1930-х"],
        pushkin_card=True,
        summary="Роман о визите Воланда в Москву, любви Мастера и Маргариты, библейской и сатирической линиях.",
        fragment="«Рукописи не горят».",
        citation="М. А. Булгаков. Мастер и Маргарита. Собрание сочинений в 8 томах. СПб.: Азбука, 2002. Т. 7.",
        public_domain_url="https://ru.wikipedia.org/wiki/Мастер_и_Маргарита",
    ),
    Source(
        id="sholokhov_tihiy",
        author="М. А. Шолохов",
        title="Тихий Дон",
        year=1940,
        genre="роман-эпопея",
        school_grade=11,
        ege_topics=["Гражданская война", "Эпопея", "Казачество"],
        pushkin_card=True,
        summary="Роман-эпопея о судьбе Григория Мелехова и казачестве в годы Первой мировой и Гражданской войн.",
        fragment="«В крови войны, в крови войны и в землю — нет ни праведных, ни виноватых».",
        citation="М. А. Шолохов. Тихий Дон. Собрание сочинений в 8 томах. М.: Сов. писатель, 1956–1960. Т. 1–4.",
        public_domain_url="https://ru.wikipedia.org/wiki/Тихий_Дон",
    ),
    Source(
        id="solzhenitsyn_ivan_denisovich",
        author="А. И. Солженицын",
        title="Один день Ивана Денисовича",
        year=1962,
        genre="повесть",
        school_grade=11,
        ege_topics=["ГУЛАГ", "Лагерная проза", "Тема памяти"],
        pushkin_card=True,
        summary="Повесть об одном дне заключённого Шухова в советском лагере — первая опубликованная в СССР книга о ГУЛАГе.",
        fragment="«Шухов отродясь не запамятовал, что в зоне человеку остаётся только хлеб да труд».",
        citation="А. И. Солженицын. Один день Ивана Денисовича. М.: Сов. Россия, 1991.",
        public_domain_url="https://www.litres.ru/aleksandr-solzhenicyn/odin-den-ivana-denisovicha/",
    ),
]


def search(query: str, limit: int = 5) -> list[Source]:
    """Простой матчинг по ключевым словам — заглушка вместо векторного поиска."""

    q = query.lower()
    scored: list[tuple[int, Source]] = []
    for s in CORPUS:
        score = 0
        haystack = " ".join(
            [
                s.author.lower(),
                s.title.lower(),
                s.genre.lower(),
                s.summary.lower(),
                s.fragment.lower(),
                " ".join(t.lower() for t in s.ege_topics),
            ]
        )
        for token in q.split():
            if token and token in haystack:
                score += 1
        if score > 0:
            scored.append((score, s))
    scored.sort(key=lambda x: (-x[0], x[1].year))
    return [s for _, s in scored[:limit]]


def by_grade(grade: int) -> list[Source]:
    return [s for s in CORPUS if s.school_grade == grade]


def by_pushkin_card() -> list[Source]:
    return [s for s in CORPUS if s.pushkin_card]


def by_id(source_id: str) -> Source | None:
    for s in CORPUS:
        if s.id == source_id:
            return s
    return None
